#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^2' focus=off
bspc rule -a dunst focus=off
bspc rule -a polkit-ukui-authentication-agent-1 state=floating 
bspc rule -a firefox:Toolkit state=floating sticky=on

xinput set-prop 13 "Coordinate Transformation Matrix" 3 0 0 0 3 0 0 0 1 &
picom --experimental-backends &
polybar mybar --config=./.config/polybar/config.ini -r &
feh --bg-scale /home/maxine/Documents/Pictures/Firefox_wallpaper.png &
touchegg &
flameshot &
/usr/lib/x86_64-linux-gnu/ukui-polkit/polkit-ukui-authentication-agent-1 &
